version: "3"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data
  api:
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    environment:
      - POSTGRES_URL=postgresql://postgres:password123@postgres/fastapi
      - SERCRET_KEY=cdecb314b87b6e3c8424538f1fbf6067aac90e9357dd8c7b70a9e67716b28f4f
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINS=60
    depends_on:
      - postgres

volumes:
  postgres-db: