"""autogenerated migration

Revision ID: 957495779c82
Revises: 126f5f099193
Create Date: 2023-03-10 18:35:30.472941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957495779c82'
down_revision = '126f5f099193'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
